[package]
name = "need-tool"
version = "0.0.2"
edition = "2024"
repository = "https://github.com/catlee/need"
license-file = "LICENSE"
description = "A simple build dependency tool"
readme = "README.md"
keywords = ["build", "incremental", "artifact", "dependency", "development"]

categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "need"
path = "src/main.rs"

[dependencies]
blake3 = "1"
fs2 = "0.4"
glob = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shell-escape = "0.1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.31", features = ["signal"] }
signal-hook = "0.4"
