set positional-arguments

revision := trim(read('upstream.lock'))
need := justfile_directory() / '../../target/debug/need'

setup:
  git init upstream
  git -C upstream fetch --depth=1 https://github.com/catppuccin/cursors.git {{revision}}
  git -C upstream checkout --detach FETCH_HEAD
  test "$(git -C upstream rev-parse HEAD)" = '{{revision}}'
  if ! git -C upstream apply --reverse --check ../upstream.patch 2>/dev/null; then git -C upstream apply --check ../upstream.patch && git -C upstream apply ../upstream.patch; fi

build *targets='theme/':
  cd upstream && '{{need}}' -j2 "$@"

verify:
  python3 verify.py

clean:
  cd upstream && '{{need}}' clean --remove-outputs
